# Generated by Django 6.0.5 on 2026-08-15 03:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sleep_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("bedtime", models.DateTimeField(blank=True, null=True)),
                ("wake_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "quality",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Muy mala"),
                            (2, "Mala"),
                            (3, "Regular"),
                            (4, "Buena"),
                            (5, "Excelente"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de sueño",
                "verbose_name_plural": "Registros de sueño",
                "db_table": "health_sleep_log",
                "ordering": ["-sleep_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "sleep_date"), name="unique_sleep_log_per_day"
                    )
                ],
            },
        ),
    ]
