# Generated by Django 6.0.5 on 2026-08-15 04:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("WALK", "Caminata"),
                            ("RUN", "Running"),
                            ("CYCLING", "Ciclismo"),
                            ("SWIMMING", "Natación"),
                            ("STRENGTH", "Fuerza"),
                            ("YOGA", "Yoga"),
                            ("SPORTS", "Deporte"),
                            ("OTHER", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ]
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MODERATE", "Moderada"),
                            ("HIGH", "Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calories_burned", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de actividad física",
                "verbose_name_plural": "Registros de actividad física",
                "db_table": "health_activity_log",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
