# Generated by Django 6.0.5 on 2026-08-15 04:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_activitylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Desayuno"),
                            ("LUNCH", "Almuerzo"),
                            ("DINNER", "Cena"),
                            ("SNACK", "Colación"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de nutrición",
                "verbose_name_plural": "Registros de nutrición",
                "db_table": "health_nutrition_log",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
