# Generated by Django 6.0.5 on 2026-08-15 04:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_nutritionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONCE_DAILY", "Una vez al día"),
                            ("TWICE_DAILY", "Dos veces al día"),
                            ("THREE_TIMES_DAILY", "Tres veces al día"),
                            ("WEEKLY", "Semanal"),
                            ("AS_NEEDED", "Según necesidad"),
                            ("OTHER", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reminder_times",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Horarios de recordatorio, formato HH:MM (ej. ['08:00', '20:00']).",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicación",
                "verbose_name_plural": "Medicaciones",
                "db_table": "health_medication",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="MedicationDoseLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("taken_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("TAKEN", "Tomada"), ("SKIPPED", "Omitida")],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_logs",
                        to="health.medication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_dose_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de dosis",
                "verbose_name_plural": "Registros de dosis",
                "db_table": "health_medication_dose_log",
                "ordering": ["-taken_at"],
            },
        ),
    ]
