# Generated by Django 6.0.5 on 2026-08-15 04:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_medication_medicationdoselog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("WEIGHT", "Peso (kg)"),
                            ("BLOOD_PRESSURE", "Presión arterial (mmHg)"),
                            ("HEART_RATE", "Frecuencia cardíaca (lpm)"),
                            ("BLOOD_GLUCOSE", "Glucosa en sangre (mg/dL)"),
                            ("BODY_TEMPERATURE", "Temperatura corporal (°C)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "secondary_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador biométrico",
                "verbose_name_plural": "Indicadores biométricos",
                "db_table": "health_biometric_log",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
