# Generated by Django 6.0.5 on 2026-05-24 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "Categoría de reserva",
                "verbose_name_plural": "Categorías de reservas",
                "db_table": "reservations_category",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT", "Cita"),
                            ("ACTIVITY", "Actividad"),
                            ("SERVICE", "Servicio"),
                            ("EVENT", "Evento"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("CONFIRMED", "Confirmado"),
                            ("COMPLETED", "Completado"),
                            ("CANCELLED", "Cancelado"),
                            ("NO_SHOW", "No asistió"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("location_name", models.CharField(blank=True, max_length=150)),
                ("location_address", models.JSONField(blank=True, default=dict)),
                ("provider_name", models.CharField(blank=True, max_length=150)),
                ("provider_contact", models.CharField(blank=True, max_length=150)),
                ("meeting_url", models.URLField(blank=True, null=True)),
                ("confirmation_code", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attending_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="households.householdnode",
                    ),
                ),
                (
                    "linked_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="assets.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="reservations.reservationcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "db_table": "reservations_reservation",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONFIRMATION", "Confirmación"),
                            ("RESULT", "Resultado"),
                            ("RECEIPT", "Recibo"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                ("file_url", models.URLField()),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de reserva",
                "verbose_name_plural": "Documentos de reservas",
                "db_table": "reservations_document",
            },
        ),
        migrations.CreateModel(
            name="ReservationReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remind_at", models.DateTimeField()),
                ("channels", models.JSONField(default=list)),
                ("sent", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recordatorio de reserva",
                "verbose_name_plural": "Recordatorios de reservas",
                "db_table": "reservations_reminder",
            },
        ),
    ]
