# Generated by Django 6.0.5 on 2026-05-24 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEALTH", "Salud"),
                            ("FITNESS", "Ejercicio"),
                            ("LEARNING", "Aprendizaje"),
                            ("HOME", "Hogar"),
                            ("FINANCE", "Finanzas"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="CUSTOM",
                        max_length=15,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PRIVATE", "Privado"), ("HOUSEHOLD", "Hogar")],
                        default="PRIVATE",
                        max_length=15,
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("frequency_config", models.JSONField(blank=True, default=dict)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("target_unit", models.CharField(blank=True, max_length=30)),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "household_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="households.householdnode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hábito",
                "verbose_name_plural": "Hábitos",
                "db_table": "routines_habit",
            },
        ),
        migrations.CreateModel(
            name="HabitStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_completed_at", models.DateField(blank=True, null=True)),
                ("total_completions", models.PositiveIntegerField(default=0)),
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to="routines.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Racha de hábito",
                "verbose_name_plural": "Rachas de hábitos",
                "db_table": "routines_habit_streak",
            },
        ),
        migrations.CreateModel(
            name="HouseholdRoutine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CLEANING", "Limpieza"),
                            ("MAINTENANCE", "Mantenimiento"),
                            ("SHOPPING", "Compras"),
                            ("COOKING", "Cocina"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="CUSTOM",
                        max_length=15,
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("ONCE", "Una vez"),
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="WEEKLY",
                        max_length=10,
                    ),
                ),
                ("recurrence_config", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_rotative", models.BooleanField(default=False)),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to="households.householdnode",
                    ),
                ),
                (
                    "linked_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routines",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rutina del hogar",
                "verbose_name_plural": "Rutinas del hogar",
                "db_table": "routines_household_routine",
            },
        ),
        migrations.CreateModel(
            name="HouseholdRoutineOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En progreso"),
                            ("COMPLETED", "Completado"),
                            ("SKIPPED", "Omitido"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("proof_image_url", models.URLField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routine_occurrences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_occurrences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="routines.householdroutine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocurrencia de rutina",
                "verbose_name_plural": "Ocurrencias de rutinas",
                "db_table": "routines_occurrence",
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logged_at", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completado"),
                            ("SKIPPED", "Omitido"),
                            ("PARTIAL", "Parcial"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="routines.habit",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de hábito",
                "verbose_name_plural": "Registros de hábitos",
                "db_table": "routines_habit_log",
                "ordering": ["-logged_at"],
                "unique_together": {("habit", "logged_at")},
            },
        ),
    ]
