# Generated by Django 6.0.5 on 2026-07-23 15:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIT_7_AREAS", "Auditoría de las siete áreas"),
                            (
                                "HEALTH_SCALE_10",
                                "Escala de salud existencial de 10 indicadores",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "db_table": "assessment_assessment",
                "ordering": ["type", "-version"],
                "unique_together": {("type", "version")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "capital_dimension",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Físico"),
                            ("EMOTIONAL", "Emocional"),
                            ("RELATIONAL", "Relacional"),
                            ("COGNITIVE", "Cognitivo"),
                            ("MORAL", "Moral"),
                            ("TRANSCENDENTAL", "Trascendental"),
                            ("STRENGTHS", "Fortalezas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scale_type",
                    models.CharField(
                        choices=[("SCALE_1_10", "Escala 1-10")],
                        default="SCALE_1_10",
                        max_length=20,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessment.assessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "db_table": "assessment_question",
                "ordering": ["assessment", "order"],
                "unique_together": {("assessment", "order")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de evaluación",
                "verbose_name_plural": "Respuestas de evaluación",
                "db_table": "assessment_response",
                "ordering": ["-created_at"],
            },
        ),
    ]
