# Generated by Django 6.0.5 on 2026-07-23 15:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_seed_health_scale_10"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "En progreso"),
                            ("COMPLETED", "Completada"),
                        ],
                        default="IN_PROGRESS",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de evaluación",
                "verbose_name_plural": "Intentos de evaluación",
                "db_table": "assessment_attempt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assessmentresponse",
            name="attempt",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessment.assessmentattempt",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="assessmentresponse",
            unique_together={("attempt", "question")},
        ),
        migrations.CreateModel(
            name="AssessmentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(auto_now_add=True)),
                ("scores_by_dimension", models.JSONField(default=dict)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="assessment.assessment",
                    ),
                ),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="assessment.assessmentattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de evaluación",
                "verbose_name_plural": "Snapshots de evaluación",
                "db_table": "assessment_snapshot",
                "ordering": ["-snapshot_date"],
            },
        ),
    ]
