# Generated by Django 6.0.5 on 2026-06-23 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('HOUSEHOLD', 'Del hogar'), ('REMINDER', 'Recordatorio')], default='PERSONAL', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending_agenda_events', to=settings.AUTH_USER_MODEL)),
                ('household_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='households.householdnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Eventos de agenda',
                'db_table': 'agenda_event',
                'ordering': ['starts_at'],
            },
        ),
    ]
