# Generated by Django 6.0.5 on 2026-05-26 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("benefits", "0001_initial"),
        ("households", "0001_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("BANK", "Cuenta bancaria"),
                            ("SAVINGS", "Ahorros"),
                            ("INVESTMENT", "Inversión"),
                            ("CREDIT", "Crédito"),
                            ("OTHER", "Otro"),
                        ],
                        default="BANK",
                        max_length=15,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("is_shared", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, max_length=10)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "household_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_accounts",
                        to="households.householdnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta financiera",
                "verbose_name_plural": "Cuentas financieras",
                "db_table": "finances_account",
            },
        ),
        migrations.CreateModel(
            name="FinanceBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensual"),
                            ("QUARTERLY", "Trimestral"),
                            ("ANNUAL", "Anual"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("alert_threshold", models.PositiveIntegerField(default=80)),
                (
                    "household_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="households.householdnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "db_table": "finances_budget",
            },
        ),
        migrations.CreateModel(
            name="FinanceBudgetExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "executed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "execution_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_TRACK", "En curso"),
                            ("WARNING", "Alerta"),
                            ("EXCEEDED", "Excedido"),
                        ],
                        default="ON_TRACK",
                        max_length=10,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="finances.financebudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de presupuesto",
                "verbose_name_plural": "Ejecuciones de presupuesto",
                "db_table": "finances_budget_execution",
            },
        ),
        migrations.CreateModel(
            name="FinanceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Ingreso"), ("EXPENSE", "Gasto")],
                        max_length=10,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=10)),
                (
                    "household_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_categories",
                        to="households.householdnode",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="finances.financecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría financiera",
                "verbose_name_plural": "Categorías financieras",
                "db_table": "finances_category",
            },
        ),
        migrations.AddField(
            model_name="financebudget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finances.financecategory",
            ),
        ),
        migrations.CreateModel(
            name="FinanceTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Ingreso"),
                            ("EXPENSE", "Gasto"),
                            ("TRANSFER", "Transferencia"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("transaction_date", models.DateField()),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_config", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("receipt_url", models.URLField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finances.financeaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.financecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="households.householdnode",
                    ),
                ),
                (
                    "linked_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="assets.asset",
                    ),
                ),
                (
                    "linked_reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "transfer_to_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transfers",
                        to="finances.financeaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción financiera",
                "verbose_name_plural": "Transacciones financieras",
                "db_table": "finances_transaction",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("billing_day", models.PositiveIntegerField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensual"),
                            ("ANNUAL", "Anual"),
                            ("WEEKLY", "Semanal"),
                            ("OTHER", "Otro"),
                        ],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("reminder_days_before", models.PositiveIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finances.financecategory",
                    ),
                ),
                (
                    "household_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to="households.householdnode",
                    ),
                ),
                (
                    "linked_benefit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_expenses",
                        to="benefits.cardbenefit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto recurrente",
                "verbose_name_plural": "Gastos recurrentes",
                "db_table": "finances_recurring_expense",
            },
        ),
    ]
