# Generated by Django 6.0.5 on 2026-07-23 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IVISnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField()),
                ("ivi", models.FloatField()),
                ("assets", models.FloatField()),
                ("liabilities", models.FloatField()),
                ("adaptation", models.FloatField()),
                ("assets_by_dimension", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ivi_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de IVI",
                "verbose_name_plural": "Snapshots de IVI",
                "db_table": "insight_ivi_snapshot",
                "ordering": ["-snapshot_date"],
                "unique_together": {("user", "snapshot_date")},
            },
        ),
    ]
