# Generated by Django 6.0.5 on 2026-05-22 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("attribute_schema", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de activo",
                "verbose_name_plural": "Categorías de activos",
                "db_table": "assets_category",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("location_in_home", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("IN_REPAIR", "En reparación"),
                            ("INACTIVE", "Inactivo"),
                            ("DISPOSED", "Dado de baja"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                (
                    "household_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="households.householdnode",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activo",
                "verbose_name_plural": "Activos",
                "db_table": "assets_asset",
            },
        ),
        migrations.CreateModel(
            name="AssetDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Factura"),
                            ("MANUAL", "Manual"),
                            ("WARRANTY", "Garantía"),
                            ("PHOTO", "Foto"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("file_url", models.URLField()),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="assets.asset",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de activo",
                "verbose_name_plural": "Documentos de activos",
                "db_table": "assets_document",
            },
        ),
        migrations.CreateModel(
            name="AssetUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField()),
                ("metric", models.CharField(max_length=50)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="assets.asset",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de uso",
                "verbose_name_plural": "Registros de uso",
                "db_table": "assets_usage_log",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventivo"),
                            ("CORRECTIVE", "Correctivo"),
                            ("INSPECTION", "Inspección"),
                            ("CLEANING", "Limpieza"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("IN_PROGRESS", "En progreso"),
                            ("COMPLETED", "Completado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("provider_name", models.CharField(blank=True, max_length=150)),
                ("provider_contact", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="assets.asset",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(blank=True, to="assets.assetdocument"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de mantenimiento",
                "verbose_name_plural": "Registros de mantenimiento",
                "db_table": "assets_maintenance_record",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "suggested_interval_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("checklist", models.JSONField(blank=True, default=list)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_templates",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de mantenimiento",
                "verbose_name_plural": "Plantillas de mantenimiento",
                "db_table": "assets_maintenance_template",
            },
        ),
    ]
