# Generated by Django 6.0.5 on 2026-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdocument',
            name='file_url',
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='file',
            field=models.FileField(blank=True, upload_to='assets/documents/'),
        ),
    ]
