# Generated by Django 6.0.5 on 2026-05-22 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("FAMILY", "Familia"),
                            ("COMMUNITY", "Comunidad"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="households.householdnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nodo de hogar",
                "verbose_name_plural": "Nodos de hogar",
                "db_table": "households_node",
            },
        ),
        migrations.CreateModel(
            name="HouseholdInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invited_email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Propietario"),
                            ("ADMIN", "Administrador"),
                            ("MEMBER", "Miembro"),
                            ("GUEST", "Invitado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.UUIDField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptada"),
                            ("EXPIRED", "Expirada"),
                            ("REVOKED", "Revocada"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="households.householdnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación",
                "verbose_name_plural": "Invitaciones",
                "db_table": "households_invitation",
            },
        ),
        migrations.CreateModel(
            name="HouseholdMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Propietario"),
                            ("ADMIN", "Administrador"),
                            ("MEMBER", "Miembro"),
                            ("GUEST", "Invitado"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=50)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="households.householdnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
                "db_table": "households_membership",
                "unique_together": {("user", "node")},
            },
        ),
    ]
