# Generated by Django 6.0.5 on 2026-07-23 16:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "capital_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Físico"),
                            ("EMOTIONAL", "Emocional"),
                            ("RELATIONAL", "Relacional"),
                            ("COGNITIVE", "Cognitivo"),
                            ("MORAL", "Moral"),
                            ("TRANSCENDENTAL", "Trascendental"),
                            ("STRENGTHS", "Fortalezas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("JOY", "Alegría"),
                            ("GRATITUDE", "Gratitud"),
                            ("CALM", "Calma"),
                            ("LOVE", "Amor"),
                            ("PRIDE", "Orgullo"),
                            ("SADNESS", "Tristeza"),
                            ("ANGER", "Ira"),
                            ("FEAR", "Miedo"),
                            ("ANXIETY", "Ansiedad"),
                            ("FRUSTRATION", "Frustración"),
                            ("LONELINESS", "Soledad"),
                            ("SHAME", "Vergüenza"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "intensity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("context_note", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro emocional",
                "verbose_name_plural": "Registros emocionales",
                "db_table": "capitals_emotional_log",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
