# Generated by Django 6.0.5 on 2026-07-23 16:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "capital_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Físico"),
                            ("EMOTIONAL", "Emocional"),
                            ("RELATIONAL", "Relacional"),
                            ("COGNITIVE", "Cognitivo"),
                            ("MORAL", "Moral"),
                            ("TRANSCENDENTAL", "Trascendental"),
                            ("STRENGTHS", "Fortalezas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "energy_gain",
                    models.TextField(blank=True, help_text="¿Qué te dio energía hoy?"),
                ),
                (
                    "energy_drain",
                    models.TextField(blank=True, help_text="¿Qué te la drenó?"),
                ),
                (
                    "avoided_conversation",
                    models.TextField(
                        blank=True, help_text="¿Qué conversación estás evitando?"
                    ),
                ),
                (
                    "attention_needed",
                    models.TextField(
                        blank=True, help_text="¿Qué parte de ti necesita atención?"
                    ),
                ),
                (
                    "gratitude",
                    models.TextField(blank=True, help_text="¿Qué merece tu gratitud?"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de diario",
                "verbose_name_plural": "Entradas de diario",
                "db_table": "capitals_journal_entry",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
