# Generated by Django 6.0.5 on 2026-05-25 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "issuer",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("AMEX", "American Express"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                ("bank", models.CharField(blank=True, max_length=100)),
                ("last_four_digits", models.CharField(blank=True, max_length=4)),
                ("color", models.CharField(blank=True, max_length=10)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "household_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="households.householdnode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta",
                "verbose_name_plural": "Tarjetas",
                "db_table": "benefits_card",
            },
        ),
        migrations.CreateModel(
            name="CardBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CASHBACK", "Cashback"),
                            ("DISCOUNT", "Descuento"),
                            ("FREE_SHIPPING", "Envío gratis"),
                            ("LOUNGE", "Sala VIP"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Porcentaje"),
                            ("FIXED", "Monto fijo"),
                            ("TWO_FOR_ONE", "2x1"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("applies_to", models.CharField(blank=True, max_length=150)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="benefits.card",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficio de tarjeta",
                "verbose_name_plural": "Beneficios de tarjetas",
                "db_table": "benefits_card_benefit",
            },
        ),
        migrations.CreateModel(
            name="CardBenefitUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("used_at", models.DateField()),
                (
                    "amount_saved",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="benefits.cardbenefit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de beneficio",
                "verbose_name_plural": "Usos de beneficios",
                "db_table": "benefits_card_benefit_usage",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("program_name", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AIRLINE", "Aerolínea"),
                            ("HOTEL", "Hotel"),
                            ("RETAIL", "Retail"),
                            ("BANK", "Banco"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("member_id", models.CharField(blank=True, max_length=100)),
                ("member_tier", models.CharField(blank=True, max_length=50)),
                (
                    "points_currency_name",
                    models.CharField(default="puntos", max_length=50),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("balance_updated_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_policy", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "household_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_programs",
                        to="households.householdnode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de fidelidad",
                "verbose_name_plural": "Programas de fidelidad",
                "db_table": "benefits_loyalty_program",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyRedemptionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "points_required",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Vuelo"),
                            ("HOTEL", "Hotel"),
                            ("PRODUCT", "Producto"),
                            ("CASHBACK", "Cashback"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption_options",
                        to="benefits.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de canje",
                "verbose_name_plural": "Opciones de canje",
                "db_table": "benefits_loyalty_redemption_option",
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EARNED", "Acumulado"),
                            ("REDEEMED", "Canjeado"),
                            ("EXPIRED", "Vencido"),
                            ("ADJUSTED", "Ajustado"),
                            ("TRANSFERRED", "Transferido"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("transaction_date", models.DateField()),
                ("source", models.CharField(blank=True, max_length=150)),
                ("reference_code", models.CharField(blank=True, max_length=100)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="benefits.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de fidelidad",
                "verbose_name_plural": "Transacciones de fidelidad",
                "db_table": "benefits_loyalty_transaction",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
