# Generated by Django 6.0.5 on 2026-07-23 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "existential_category",
                    models.CharField(
                        choices=[
                            ("OBLIGATIONS", "Obligaciones"),
                            ("INNER_NOURISHMENT", "Nutrición interior"),
                            ("BONDS", "Vínculos"),
                            ("TRANSCENDENCE", "Trascendencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "energy_tag",
                    models.CharField(
                        choices=[
                            ("ENERGIZES", "Energiza"),
                            ("NEUTRAL", "Neutro"),
                            ("DRAINS", "Drena"),
                        ],
                        max_length=10,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planificado"),
                            ("FULFILLED", "Cumplido"),
                            ("OMITTED", "Omitido"),
                        ],
                        default="PLANNED",
                        max_length=10,
                    ),
                ),
                ("source_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="agenda.timeblock",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloque de tiempo",
                "verbose_name_plural": "Bloques de tiempo",
                "db_table": "agenda_time_block",
                "ordering": ["-start_datetime", "-created_at"],
            },
        ),
    ]
