# Generated by Django 6.0.5 on 2026-07-30 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Mantenimiento"),
                            ("HABIT", "Hábito"),
                            ("ROUTINE", "Rutina"),
                            ("RESERVATION", "Reserva"),
                            ("BENEFIT", "Beneficio"),
                            ("FINANCE_BUDGET", "Presupuesto"),
                            ("FINANCE_RECURRING", "Gasto recurrente"),
                            ("LOYALTY_EXPIRY", "Puntos por vencer"),
                            ("INSIGHT_DIMENSION", "Alerta de dimensión IVI"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                ("body_template", models.TextField()),
                ("default_channels", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Plantilla de alerta",
                "verbose_name_plural": "Plantillas de alertas",
                "db_table": "notifications_alert_template",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Mantenimiento"),
                            ("HABIT", "Hábito"),
                            ("ROUTINE", "Rutina"),
                            ("RESERVATION", "Reserva"),
                            ("BENEFIT", "Beneficio"),
                            ("FINANCE_BUDGET", "Presupuesto"),
                            ("FINANCE_RECURRING", "Gasto recurrente"),
                            ("LOYALTY_EXPIRY", "Puntos por vencer"),
                            ("INSIGHT_DIMENSION", "Alerta de dimensión IVI"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("channels", models.JSONField(default=list)),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Fallido"),
                            ("READ", "Leído"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "db_table": "notifications_alert",
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
